[build-system]
<<<<<<< HEAD
requires = ["setuptools>=42", "wheel", "build", "Cython>=0.29.23", "numpy"]
=======
requires = ["setuptools>=42", "wheel", "build", "Cython>=0.29.23", "numpy==1.20.3"]
>>>>>>> parent of 337bd3a (Revert "Completing translation")
build-backend = "setuptools.build_meta"
