name: build and release cubist

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches:
      - master
      - main
      - release
      - test
      - dev
  release:
    branches:
      - release
    types:
      - created

jobs:
  build:
    name: Test and build on Python ${{ matrix.python_version }} and ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Enable Developer Command Prompt for Windows
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Add sys/time.h for Windows
      if: matrix.os == 'windows-latest'
      run: |
        mv winsys/ cubist/sys
      
    - name: Remove winsys folder for non-Windows OSes
      if: matrix.os != 'windows-latest'
      run: |
        rm -r winsys/
    
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install setuptools wheel build cython
        pip3 install flake8 pytest pytest-cov numpy
        pip install -e .

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pip install pytest
        pytest --cov=com --cov-report=xml --cov-report=html
    
    - name: Build wheel
      run: |
        pip install pep517 wheel
        python -m pep517.build --source --binary --out-dir dist/ .
    
    - name: Upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  release:
    # release only tagged commits to pypi / github
    name: release distribution
    needs: build
    if: github.ref == 'refs/heads/release'
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: mkdir
      run: |
        mkdir dist

    - name: download artifacts
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - name: ls
      run: |
        ls dist/

    # test publish to pypi
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    # github upload release asset
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        name: latest
        tag_name: latest
        body: Latest version of distribution
        files: |
          dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # publish only tagged commits to pypi
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
