name: Test, build, and release cython package

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches:
    - master
    - main
    - release
    - test
    - dev

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest] # [ macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install tox tox-gh-actions

    - name: Test with tox
      run: |
        tox
      env:
        PLATFORM: ${{ matrix.platform  }}

    # if successful build -> release
    - name: Build
      run: |
        pip3 install setuptools build wheel auditwheel
        python3  -m build --sdist --wheel .
        auditwheel repair dist/*
        rm dist/*-linux_x86_64.whl

    # test publish to pypi
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    # github upload release asset
    - name: Upload Release Asset
      if: ${{ env.GITHUB_REF=='refs/heads/release' }}
      uses: softprops/action-gh-release@v1
      with:
        name: latest
        tag_name: latest
        body: Latest version of distribution
        files: |
          dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # publish to pypi
    - name: Publish distribution 📦 to PyPI
      if: ${{ env.GITHUB_REF=='refs/heads/release' }}
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
