name: Test and Lint Cubist

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  pull_request:
    types:
      - synchronize
    branches:
      - dev
      - main
  workflow_call:

jobs:
  test:
    name: Test and lint on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    # - name: Enable Developer Command Prompt for Windows
    #   if: matrix.os == 'windows-latest'
    #   uses: ilammy/msvc-dev-cmd@v1
    #   with:
    #     vsversion: "2019"
    
    - name: Add sys/time.h for Windows
      if: matrix.os == 'windows-latest'
      run: |
        mv winsys/ cubist/sys
      
    - name: Remove winsys folder for non-Windows OS
      if: matrix.os != 'windows-latest'
      run: |
        rm -r winsys/
    
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install setuptools wheel build cython
        pip3 install flake8 pytest pytest-cov numpy
        pip3 install -r requirements.txt
        python setup.py build_ext --inplace

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pip install pytest
        pytest --cov=com --cov-report=xml --cov-report=html
